version: '3.3'

# Erro comum se o sonarapp n subir
# sudo sysctl -w vm.max_map_count=262144

# Senha e usuario padrao
# admin

# echo 'vm.max_map_count=262144' >> /etc/sysctl.conf
# sysctl -p

networks:
  sonar-network:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  
services:
  sonarqube-db:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart:
      unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sonar
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    networks:
      - sonar-network

  sonarqube-app:
    image: sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    restart:
      unless-stopped
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
    ports:
      - "9000:9000"
    networks:
      - sonar-network
